import { create } from 'zustand'

export const registerationStore = create((set) => ({
  formStep: 0,
  selectedAccountType: 'individual',
  paymentMode: "yearly",
  individualYearlyFee: '24.99',
  individualMonthlyFee: '34.99',
  familyMonthlyFee: "54.99",
  familyYearlyFee: "44.99",
  userInfo: {
    _id: "",
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    isChildUser: "",
    address: "",
    city: "",
    province: "",
    postalCode: "",
    paymentMode: "",
    accountType: '',
    childAccounts: [],
  },
  setUserInfo: (userInfoData) => set((state) => ({ userInfo: userInfoData })),
  changeSelectedAccountType: (accountType) => set((state) => ({ selectedAccountType: accountType })),
  increaseFormStep: () => set((state) => ({ formStep: state.formStep + 1 })),
  decreaseFormStep: () => set((state) => ({ formStep: state.formStep - 1 })),
  setPaymentMode: (value) => set((state) => ({ paymentMode: value })),
  registerationFormData: {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    password: '',
    address: '',
    city: '',
    province: '',
    postalCode: '',
    country: 'Canada',
    creditCardNumber: '',
    creditCardExpiry: '',
    creditCardCvc: ''
  },
  handleRegisterationFormDataChange: (name, value) => set((state) => ({ registerationFormData: { ...state.registerationFormData, [name]: value } })),
  clearForms: () => set({
    formStep: 0,
    registerationFormData: {
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      password: '',
      address: '',
      city: '',
      province: '',
      postalCode: '',
      country: 'Canada',
      creditCardNumber: '',
      creditCardExpiry: '',
      creditCardCvc: ''
    },
  })
}))